[package]
name = "drain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indextree = "4.5.0"
regex = "1"
log = "0.4.17"
[dev-dependencies]
simple_logger = "4.0.0"